// <auto-generated />
namespace _1721050522_Trinh_Thu_Huong_BTL_LTQL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Create_Table_CHITIETKHENTHUONGKYLUAT : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Create_Table_CHITIETKHENTHUONGKYLUAT));
        
        string IMigrationMetadata.Id
        {
            get { return "202103100144289_Create_Table_CHITIETKHENTHUONG-KYLUAT"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
