namespace _1721050522_Trinh_Thu_Huong_BTL_LTQL.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class Create_database : DbMigration
    {
        public override void Up()
        {
            DropPrimaryKey("dbo.BANGCHAMCONGs");
            DropPrimaryKey("dbo.BANGLUONGs");
            DropPrimaryKey("dbo.CHITIETDUANs");
            DropPrimaryKey("dbo.CONGTACs");
            DropPrimaryKey("dbo.NHANVIENs");
            DropPrimaryKey("dbo.TRINHDO_CHUYENMONs");
            DropPrimaryKey("dbo.TRINHDO_NGOAINGUs");
            AddColumn("dbo.BANGCHAMCONGs", "MaCC", c => c.String(unicode: false));
            AddColumn("dbo.BANGLUONGs", "MaLuong", c => c.String(unicode: false));
            AddColumn("dbo.CHITIETDUANs", "TenDuAn", c => c.String(unicode: false));
            AddColumn("dbo.CHITIETDUANs", "Ngaybatdau", c => c.DateTime(nullable: false));
            AddColumn("dbo.CHITIETDUANs", "Ngaygiahan", c => c.DateTime(nullable: false));
            AddColumn("dbo.CHITIETDUANs", "Ngayketthuc", c => c.DateTime(nullable: false));
            AddColumn("dbo.CHITIETDUANs", "SoLuong", c => c.String(unicode: false));
            AddColumn("dbo.CHITIETDUANs", "DonGia", c => c.String(unicode: false));
            AddColumn("dbo.CHITIETDUANs", "ChietKhau", c => c.String(unicode: false));
            AddColumn("dbo.CHUCVUs", "NHANVIENs_MaNV", c => c.String(maxLength: 128, unicode: false));
            AddColumn("dbo.CHUYENMONs", "TRINHDO_CHUYENMONs_MaNV", c => c.String(maxLength: 50, unicode: false));
            AddColumn("dbo.CONGTACs", "MaCT", c => c.String(unicode: false));
            AddColumn("dbo.DUANs", "MaNV", c => c.String(unicode: false));
            AddColumn("dbo.NHANVIENs", "BANGCHAMCONGs_MaNhanVien", c => c.String(maxLength: 50, unicode: false));
            AddColumn("dbo.NHANVIENs", "BANGLUONGs_MaNhanVien", c => c.String(maxLength: 50, unicode: false));
            AddColumn("dbo.NHANVIENs", "CONGTACs_MaNV", c => c.String(maxLength: 50, unicode: false));
            AddColumn("dbo.NHANVIENs", "DUANs_TenDuAn", c => c.String(maxLength: 50, unicode: false));
            AddColumn("dbo.NHANVIENs", "TRINHDO_CHUYENMONs_MaNV", c => c.String(maxLength: 50, unicode: false));
            AddColumn("dbo.NHANVIENs", "TRINHDO_NGOAINGUs_MaTrinhDo", c => c.String(maxLength: 50, unicode: false));
            AddColumn("dbo.PHONGBANs", "NHANVIENs_MaNV", c => c.String(maxLength: 128, unicode: false));
            AddColumn("dbo.TRINHDO_CHUYENMONs", "STT", c => c.String(unicode: false));
            AddColumn("dbo.TRINHDO_NGOAINGUs", "MaTrinhDoNN", c => c.String(unicode: false));
            AddColumn("dbo.TRINHDOs", "TRINHDO_CHUYENMONs_MaNV", c => c.String(maxLength: 50, unicode: false));
            AlterColumn("dbo.BANGCHAMCONGs", "TenNhanVien", c => c.String(unicode: false));
            AlterColumn("dbo.BANGCHAMCONGs", "MaNhanVien", c => c.String(nullable: false, maxLength: 50, unicode: false));
            AlterColumn("dbo.BANGLUONGs", "TenNhanVien", c => c.String(unicode: false));
            AlterColumn("dbo.BANGLUONGs", "MaNhanVien", c => c.String(nullable: false, maxLength: 50, unicode: false));
            AlterColumn("dbo.CHITIETDUANs", "MaNhanVien", c => c.String(unicode: false));
            AlterColumn("dbo.CHITIETDUANs", "MaDuAn", c => c.String(nullable: false, maxLength: 50, unicode: false));
            AlterColumn("dbo.CONGTACs", "CongViec", c => c.String(unicode: false));
            AlterColumn("dbo.CONGTACs", "MaNV", c => c.String(nullable: false, maxLength: 50, unicode: false));
            AlterColumn("dbo.DUANs", "MaDuAn", c => c.String(maxLength: 50, unicode: false));
            AlterColumn("dbo.NHANVIENs", "HoTen", c => c.String(unicode: false));
            AlterColumn("dbo.NHANVIENs", "MaNV", c => c.String(nullable: false, maxLength: 128, unicode: false));
            AlterColumn("dbo.NHANVIENs", "GioiTinh", c => c.String(nullable: false, maxLength: 50, unicode: false));
            AlterColumn("dbo.TRINHDO_CHUYENMONs", "MaTrinhDo", c => c.String(unicode: false));
            AlterColumn("dbo.TRINHDO_CHUYENMONs", "MaNV", c => c.String(nullable: false, maxLength: 50, unicode: false));
            AlterColumn("dbo.TRINHDO_NGOAINGUs", "TenTrinhDo", c => c.String(unicode: false));
            AlterColumn("dbo.TRINHDO_NGOAINGUs", "MaTrinhDo", c => c.String(nullable: false, maxLength: 50, unicode: false));
            AddPrimaryKey("dbo.BANGCHAMCONGs", "MaNhanVien");
            AddPrimaryKey("dbo.BANGLUONGs", "MaNhanVien");
            AddPrimaryKey("dbo.CHITIETDUANs", "MaDuAn");
            AddPrimaryKey("dbo.CONGTACs", "MaNV");
            AddPrimaryKey("dbo.NHANVIENs", "MaNV");
            AddPrimaryKey("dbo.TRINHDO_CHUYENMONs", "MaNV");
            AddPrimaryKey("dbo.TRINHDO_NGOAINGUs", "MaTrinhDo");
            CreateIndex("dbo.NHANVIENs", "BANGCHAMCONGs_MaNhanVien");
            CreateIndex("dbo.NHANVIENs", "BANGLUONGs_MaNhanVien");
            CreateIndex("dbo.NHANVIENs", "CONGTACs_MaNV");
            CreateIndex("dbo.NHANVIENs", "DUANs_TenDuAn");
            CreateIndex("dbo.NHANVIENs", "TRINHDO_CHUYENMONs_MaNV");
            CreateIndex("dbo.NHANVIENs", "TRINHDO_NGOAINGUs_MaTrinhDo");
            CreateIndex("dbo.CHUCVUs", "NHANVIENs_MaNV");
            CreateIndex("dbo.DUANs", "MaDuAn");
            CreateIndex("dbo.PHONGBANs", "NHANVIENs_MaNV");
            CreateIndex("dbo.CHUYENMONs", "TRINHDO_CHUYENMONs_MaNV");
            CreateIndex("dbo.TRINHDOs", "TRINHDO_CHUYENMONs_MaNV");
            AddForeignKey("dbo.NHANVIENs", "BANGCHAMCONGs_MaNhanVien", "dbo.BANGCHAMCONGs", "MaNhanVien");
            AddForeignKey("dbo.NHANVIENs", "BANGLUONGs_MaNhanVien", "dbo.BANGLUONGs", "MaNhanVien");
            AddForeignKey("dbo.CHUCVUs", "NHANVIENs_MaNV", "dbo.NHANVIENs", "MaNV");
            AddForeignKey("dbo.NHANVIENs", "CONGTACs_MaNV", "dbo.CONGTACs", "MaNV");
            AddForeignKey("dbo.DUANs", "MaDuAn", "dbo.CHITIETDUANs", "MaDuAn");
            AddForeignKey("dbo.NHANVIENs", "DUANs_TenDuAn", "dbo.DUANs", "TenDuAn");
            AddForeignKey("dbo.PHONGBANs", "NHANVIENs_MaNV", "dbo.NHANVIENs", "MaNV");
            AddForeignKey("dbo.CHUYENMONs", "TRINHDO_CHUYENMONs_MaNV", "dbo.TRINHDO_CHUYENMONs", "MaNV");
            AddForeignKey("dbo.NHANVIENs", "TRINHDO_CHUYENMONs_MaNV", "dbo.TRINHDO_CHUYENMONs", "MaNV");
            AddForeignKey("dbo.TRINHDOs", "TRINHDO_CHUYENMONs_MaNV", "dbo.TRINHDO_CHUYENMONs", "MaNV");
            AddForeignKey("dbo.NHANVIENs", "TRINHDO_NGOAINGUs_MaTrinhDo", "dbo.TRINHDO_NGOAINGUs", "MaTrinhDo");
            DropColumn("dbo.DUANs", "Ngaybatdau");
            DropColumn("dbo.DUANs", "Ngaygiahan");
            DropColumn("dbo.DUANs", "Ngayketthuc");
            DropColumn("dbo.DUANs", "SoLuong");
            DropColumn("dbo.DUANs", "DonGia");
            DropColumn("dbo.DUANs", "ChietKhau");
        }
        
        public override void Down()
        {
            AddColumn("dbo.DUANs", "ChietKhau", c => c.String(unicode: false));
            AddColumn("dbo.DUANs", "DonGia", c => c.String(unicode: false));
            AddColumn("dbo.DUANs", "SoLuong", c => c.String(unicode: false));
            AddColumn("dbo.DUANs", "Ngayketthuc", c => c.DateTime(nullable: false));
            AddColumn("dbo.DUANs", "Ngaygiahan", c => c.DateTime(nullable: false));
            AddColumn("dbo.DUANs", "Ngaybatdau", c => c.DateTime(nullable: false));
            DropForeignKey("dbo.NHANVIENs", "TRINHDO_NGOAINGUs_MaTrinhDo", "dbo.TRINHDO_NGOAINGUs");
            DropForeignKey("dbo.TRINHDOs", "TRINHDO_CHUYENMONs_MaNV", "dbo.TRINHDO_CHUYENMONs");
            DropForeignKey("dbo.NHANVIENs", "TRINHDO_CHUYENMONs_MaNV", "dbo.TRINHDO_CHUYENMONs");
            DropForeignKey("dbo.CHUYENMONs", "TRINHDO_CHUYENMONs_MaNV", "dbo.TRINHDO_CHUYENMONs");
            DropForeignKey("dbo.PHONGBANs", "NHANVIENs_MaNV", "dbo.NHANVIENs");
            DropForeignKey("dbo.NHANVIENs", "DUANs_TenDuAn", "dbo.DUANs");
            DropForeignKey("dbo.DUANs", "MaDuAn", "dbo.CHITIETDUANs");
            DropForeignKey("dbo.NHANVIENs", "CONGTACs_MaNV", "dbo.CONGTACs");
            DropForeignKey("dbo.CHUCVUs", "NHANVIENs_MaNV", "dbo.NHANVIENs");
            DropForeignKey("dbo.NHANVIENs", "BANGLUONGs_MaNhanVien", "dbo.BANGLUONGs");
            DropForeignKey("dbo.NHANVIENs", "BANGCHAMCONGs_MaNhanVien", "dbo.BANGCHAMCONGs");
            DropIndex("dbo.TRINHDOs", new[] { "TRINHDO_CHUYENMONs_MaNV" });
            DropIndex("dbo.CHUYENMONs", new[] { "TRINHDO_CHUYENMONs_MaNV" });
            DropIndex("dbo.PHONGBANs", new[] { "NHANVIENs_MaNV" });
            DropIndex("dbo.DUANs", new[] { "MaDuAn" });
            DropIndex("dbo.CHUCVUs", new[] { "NHANVIENs_MaNV" });
            DropIndex("dbo.NHANVIENs", new[] { "TRINHDO_NGOAINGUs_MaTrinhDo" });
            DropIndex("dbo.NHANVIENs", new[] { "TRINHDO_CHUYENMONs_MaNV" });
            DropIndex("dbo.NHANVIENs", new[] { "DUANs_TenDuAn" });
            DropIndex("dbo.NHANVIENs", new[] { "CONGTACs_MaNV" });
            DropIndex("dbo.NHANVIENs", new[] { "BANGLUONGs_MaNhanVien" });
            DropIndex("dbo.NHANVIENs", new[] { "BANGCHAMCONGs_MaNhanVien" });
            DropPrimaryKey("dbo.TRINHDO_NGOAINGUs");
            DropPrimaryKey("dbo.TRINHDO_CHUYENMONs");
            DropPrimaryKey("dbo.NHANVIENs");
            DropPrimaryKey("dbo.CONGTACs");
            DropPrimaryKey("dbo.CHITIETDUANs");
            DropPrimaryKey("dbo.BANGLUONGs");
            DropPrimaryKey("dbo.BANGCHAMCONGs");
            AlterColumn("dbo.TRINHDO_NGOAINGUs", "MaTrinhDo", c => c.String(unicode: false));
            AlterColumn("dbo.TRINHDO_NGOAINGUs", "TenTrinhDo", c => c.String(nullable: false, maxLength: 50, unicode: false));
            AlterColumn("dbo.TRINHDO_CHUYENMONs", "MaNV", c => c.String(unicode: false));
            AlterColumn("dbo.TRINHDO_CHUYENMONs", "MaTrinhDo", c => c.String(nullable: false, maxLength: 50, unicode: false));
            AlterColumn("dbo.NHANVIENs", "GioiTinh", c => c.String(unicode: false));
            AlterColumn("dbo.NHANVIENs", "MaNV", c => c.String(unicode: false));
            AlterColumn("dbo.NHANVIENs", "HoTen", c => c.String(nullable: false, maxLength: 30, unicode: false));
            AlterColumn("dbo.DUANs", "MaDuAn", c => c.String(unicode: false));
            AlterColumn("dbo.CONGTACs", "MaNV", c => c.String(unicode: false));
            AlterColumn("dbo.CONGTACs", "CongViec", c => c.String(nullable: false, maxLength: 50, unicode: false));
            AlterColumn("dbo.CHITIETDUANs", "MaDuAn", c => c.String(unicode: false));
            AlterColumn("dbo.CHITIETDUANs", "MaNhanVien", c => c.String(nullable: false, maxLength: 50, unicode: false));
            AlterColumn("dbo.BANGLUONGs", "MaNhanVien", c => c.String(unicode: false));
            AlterColumn("dbo.BANGLUONGs", "TenNhanVien", c => c.String(nullable: false, maxLength: 50, unicode: false));
            AlterColumn("dbo.BANGCHAMCONGs", "MaNhanVien", c => c.String(unicode: false));
            AlterColumn("dbo.BANGCHAMCONGs", "TenNhanVien", c => c.String(nullable: false, maxLength: 50, unicode: false));
            DropColumn("dbo.TRINHDOs", "TRINHDO_CHUYENMONs_MaNV");
            DropColumn("dbo.TRINHDO_NGOAINGUs", "MaTrinhDoNN");
            DropColumn("dbo.TRINHDO_CHUYENMONs", "STT");
            DropColumn("dbo.PHONGBANs", "NHANVIENs_MaNV");
            DropColumn("dbo.NHANVIENs", "TRINHDO_NGOAINGUs_MaTrinhDo");
            DropColumn("dbo.NHANVIENs", "TRINHDO_CHUYENMONs_MaNV");
            DropColumn("dbo.NHANVIENs", "DUANs_TenDuAn");
            DropColumn("dbo.NHANVIENs", "CONGTACs_MaNV");
            DropColumn("dbo.NHANVIENs", "BANGLUONGs_MaNhanVien");
            DropColumn("dbo.NHANVIENs", "BANGCHAMCONGs_MaNhanVien");
            DropColumn("dbo.DUANs", "MaNV");
            DropColumn("dbo.CONGTACs", "MaCT");
            DropColumn("dbo.CHUYENMONs", "TRINHDO_CHUYENMONs_MaNV");
            DropColumn("dbo.CHUCVUs", "NHANVIENs_MaNV");
            DropColumn("dbo.CHITIETDUANs", "ChietKhau");
            DropColumn("dbo.CHITIETDUANs", "DonGia");
            DropColumn("dbo.CHITIETDUANs", "SoLuong");
            DropColumn("dbo.CHITIETDUANs", "Ngayketthuc");
            DropColumn("dbo.CHITIETDUANs", "Ngaygiahan");
            DropColumn("dbo.CHITIETDUANs", "Ngaybatdau");
            DropColumn("dbo.CHITIETDUANs", "TenDuAn");
            DropColumn("dbo.BANGLUONGs", "MaLuong");
            DropColumn("dbo.BANGCHAMCONGs", "MaCC");
            AddPrimaryKey("dbo.TRINHDO_NGOAINGUs", "TenTrinhDo");
            AddPrimaryKey("dbo.TRINHDO_CHUYENMONs", "MaTrinhDo");
            AddPrimaryKey("dbo.NHANVIENs", "HoTen");
            AddPrimaryKey("dbo.CONGTACs", "CongViec");
            AddPrimaryKey("dbo.CHITIETDUANs", "MaNhanVien");
            AddPrimaryKey("dbo.BANGLUONGs", "TenNhanVien");
            AddPrimaryKey("dbo.BANGCHAMCONGs", "TenNhanVien");
        }
    }
}
